module "iac_aws_samuel" {
  # aws_iam_access_key_akiauddrcmztbllng45q_status                                                                                                                = "Active"
  # aws_iam_access_key_akiauddrcmztbllng45q_tc_category                                                                                                           = "iam"
  # aws_iam_access_key_akiauddrcmztbllng45q_user                                                                                                                  = "exportiacaws"
  # aws_iam_group_admin_name                                                                                                                                      = "admin"
  # aws_iam_group_admin_path                                                                                                                                      = "/"
  # aws_iam_group_admin_tc_category                                                                                                                               = "iam"
  # aws_iam_group_membership_admin_group                                                                                                                          = "admin"
  # aws_iam_group_membership_admin_name                                                                                                                           = ""
  # aws_iam_group_membership_admin_tc_category                                                                                                                    = "iam"
  # aws_iam_group_membership_admin_users                                                                                                                          = ["exportiacaws"]
  # aws_iam_group_policy_attachment_admin_arn_aws_iam__aws_policy_administratoraccess_group                                                                       = "admin"
  # aws_iam_group_policy_attachment_admin_arn_aws_iam__aws_policy_administratoraccess_policy_arn                                                                  = "arn:aws:iam::aws:policy/AdministratorAccess"
  # aws_iam_group_policy_attachment_admin_arn_aws_iam__aws_policy_administratoraccess_tc_category                                                                 = "iam"
  # aws_iam_role_awsserviceroleforawslicensemanagerrole_assume_role_policy                                                                                        = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"license-manager.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_awsserviceroleforawslicensemanagerrole_description                                                                                               = "Service linked role for License Manager."
  # aws_iam_role_awsserviceroleforawslicensemanagerrole_managed_policy_arns                                                                                       = ["arn:aws:iam::aws:policy/aws-service-role/AWSLicenseManagerServiceRolePolicy"]
  # aws_iam_role_awsserviceroleforawslicensemanagerrole_max_session_duration                                                                                      = 3600
  # aws_iam_role_awsserviceroleforawslicensemanagerrole_name                                                                                                      = "AWSServiceRoleForAWSLicenseManagerRole"
  # aws_iam_role_awsserviceroleforawslicensemanagerrole_path                                                                                                      = "/aws-service-role/license-manager.amazonaws.com/"
  # aws_iam_role_awsserviceroleforawslicensemanagerrole_tc_category                                                                                               = "iam"
  # aws_iam_role_awsserviceroleforsupport_assume_role_policy                                                                                                      = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"support.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_awsserviceroleforsupport_description                                                                                                             = "Enables resource access for AWS to provide billing, administrative and support services"
  # aws_iam_role_awsserviceroleforsupport_managed_policy_arns                                                                                                     = ["arn:aws:iam::aws:policy/aws-service-role/AWSSupportServiceRolePolicy"]
  # aws_iam_role_awsserviceroleforsupport_max_session_duration                                                                                                    = 3600
  # aws_iam_role_awsserviceroleforsupport_name                                                                                                                    = "AWSServiceRoleForSupport"
  # aws_iam_role_awsserviceroleforsupport_path                                                                                                                    = "/aws-service-role/support.amazonaws.com/"
  # aws_iam_role_awsserviceroleforsupport_tc_category                                                                                                             = "iam"
  # aws_iam_role_awsservicerolefortrustedadvisor_assume_role_policy                                                                                               = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"trustedadvisor.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_awsservicerolefortrustedadvisor_description                                                                                                      = "Access for the AWS Trusted Advisor Service to help reduce cost, increase performance, and improve security of your AWS environment."
  # aws_iam_role_awsservicerolefortrustedadvisor_managed_policy_arns                                                                                              = ["arn:aws:iam::aws:policy/aws-service-role/AWSTrustedAdvisorServiceRolePolicy"]
  # aws_iam_role_awsservicerolefortrustedadvisor_max_session_duration                                                                                             = 3600
  # aws_iam_role_awsservicerolefortrustedadvisor_name                                                                                                             = "AWSServiceRoleForTrustedAdvisor"
  # aws_iam_role_awsservicerolefortrustedadvisor_path                                                                                                             = "/aws-service-role/trustedadvisor.amazonaws.com/"
  # aws_iam_role_awsservicerolefortrustedadvisor_tc_category                                                                                                      = "iam"
  # aws_iam_role_policy_attachment_awsserviceroleforawslicensemanagerrole_arn_aws_iam__aws_policy_aws_service_role_awslicensemanagerservicerolepolicy_policy_arn  = "arn:aws:iam::aws:policy/aws-service-role/AWSLicenseManagerServiceRolePolicy"
  # aws_iam_role_policy_attachment_awsserviceroleforawslicensemanagerrole_arn_aws_iam__aws_policy_aws_service_role_awslicensemanagerservicerolepolicy_role        = "AWSServiceRoleForAWSLicenseManagerRole"
  # aws_iam_role_policy_attachment_awsserviceroleforawslicensemanagerrole_arn_aws_iam__aws_policy_aws_service_role_awslicensemanagerservicerolepolicy_tc_category = "iam"
  # aws_iam_role_policy_attachment_awsserviceroleforsupport_arn_aws_iam__aws_policy_aws_service_role_awssupportservicerolepolicy_policy_arn                       = "arn:aws:iam::aws:policy/aws-service-role/AWSSupportServiceRolePolicy"
  # aws_iam_role_policy_attachment_awsserviceroleforsupport_arn_aws_iam__aws_policy_aws_service_role_awssupportservicerolepolicy_role                             = "AWSServiceRoleForSupport"
  # aws_iam_role_policy_attachment_awsserviceroleforsupport_arn_aws_iam__aws_policy_aws_service_role_awssupportservicerolepolicy_tc_category                      = "iam"
  # aws_iam_role_policy_attachment_awsservicerolefortrustedadvisor_arn_aws_iam__aws_policy_aws_service_role_awstrustedadvisorservicerolepolicy_policy_arn         = "arn:aws:iam::aws:policy/aws-service-role/AWSTrustedAdvisorServiceRolePolicy"
  # aws_iam_role_policy_attachment_awsservicerolefortrustedadvisor_arn_aws_iam__aws_policy_aws_service_role_awstrustedadvisorservicerolepolicy_role               = "AWSServiceRoleForTrustedAdvisor"
  # aws_iam_role_policy_attachment_awsservicerolefortrustedadvisor_arn_aws_iam__aws_policy_aws_service_role_awstrustedadvisorservicerolepolicy_tc_category        = "iam"
  # aws_iam_user_exportiacaws_name                                                                                                                                = "exportiacaws"
  # aws_iam_user_exportiacaws_path                                                                                                                                = "/"
  # aws_iam_user_exportiacaws_tc_category                                                                                                                         = "iam"
  # aws_instance_jobpay01__tc_tags_all_name                                                                                                                       = "jobpay01"
  # aws_instance_jobpay01__tc_tags_name                                                                                                                           = "jobpay01"
  # aws_instance_jobpay01_ami                                                                                                                                     = "ami-09e67e426f25ce0d7"
  # aws_instance_jobpay01_availability_zone                                                                                                                       = "us-east-1d"
  # aws_instance_jobpay01_cpu_core_count                                                                                                                          = 1
  # aws_instance_jobpay01_cpu_threads_per_core                                                                                                                    = 1
  # aws_instance_jobpay01_credit_specification_cpu_credits                                                                                                        = "standard"
  # aws_instance_jobpay01_instance_initiated_shutdown_behavior                                                                                                    = "stop"
  # aws_instance_jobpay01_instance_type                                                                                                                           = "t2.micro"
  # aws_instance_jobpay01_key_name                                                                                                                                = "tanamao"
  # aws_instance_jobpay01_metadata_options_http_endpoint                                                                                                          = "enabled"
  # aws_instance_jobpay01_metadata_options_http_put_response_hop_limit                                                                                            = 1
  # aws_instance_jobpay01_metadata_options_http_tokens                                                                                                            = "optional"
  # aws_instance_jobpay01_private_ip                                                                                                                              = "172.31.81.188"
  # aws_instance_jobpay01_root_block_device_delete_on_termination                                                                                                 = true
  # aws_instance_jobpay01_root_block_device_iops                                                                                                                  = 100
  # aws_instance_jobpay01_root_block_device_volume_size                                                                                                           = 8
  # aws_instance_jobpay01_root_block_device_volume_type                                                                                                           = "gp2"
  # aws_instance_jobpay01_security_groups                                                                                                                         = ["launch-wizard-4"]
  # aws_instance_jobpay01_source_dest_check                                                                                                                       = true
  # aws_instance_jobpay01_subnet_id                                                                                                                               = "subnet-a0f2ac81"
  # aws_instance_jobpay01_tc_category                                                                                                                             = "ec2"
  # aws_instance_jobpay01_tenancy                                                                                                                                 = "default"
  # aws_instance_jobpay01_vpc_security_group_ids                                                                                                                  = ["sg-09627a4b90bb62da5"]
  # aws_internet_gateway_igw_ee64b794_tc_category                                                                                                                 = "vpc"
  # aws_internet_gateway_igw_ee64b794_vpc_id                                                                                                                      = "vpc-9adfb3e7"
  # aws_key_pair_exportiacaws_key_name                                                                                                                            = "exportiacaws"
  # aws_key_pair_exportiacaws_public_key                                                                                                                          = ""
  # aws_key_pair_exportiacaws_tc_category                                                                                                                         = "ec2"
  # aws_key_pair_tanamao_key_name                                                                                                                                 = "tanamao"
  # aws_key_pair_tanamao_public_key                                                                                                                               = ""
  # aws_key_pair_tanamao_tc_category                                                                                                                              = "ec2"
  # aws_route53_resolver_rule_association_rslvr_autodefined_assoc_vpc_9adfb3e7_internet_resolver_name                                                             = "System Rule Association"
  # aws_route53_resolver_rule_association_rslvr_autodefined_assoc_vpc_9adfb3e7_internet_resolver_resolver_rule_id                                                 = "rslvr-autodefined-rr-internet-resolver"
  # aws_route53_resolver_rule_association_rslvr_autodefined_assoc_vpc_9adfb3e7_internet_resolver_tc_category                                                      = "route53_resolver"
  # aws_route53_resolver_rule_association_rslvr_autodefined_assoc_vpc_9adfb3e7_internet_resolver_vpc_id                                                           = "vpc-9adfb3e7"
  # aws_s3_bucket_lab01_dev4__tc_tags_all_name                                                                                                                    = "lab01-dev4"
  # aws_s3_bucket_lab01_dev4__tc_tags_name                                                                                                                        = "lab01-dev4"
  # aws_s3_bucket_lab01_dev4_arn                                                                                                                                  = "arn:aws:s3:::lab01-dev4"
  # aws_s3_bucket_lab01_dev4_bucket                                                                                                                               = "lab01-dev4"
  # aws_s3_bucket_lab01_dev4_hosted_zone_id                                                                                                                       = "Z3AQBSTGFYJSTF"
  # aws_s3_bucket_lab01_dev4_request_payer                                                                                                                        = "BucketOwner"
  # aws_s3_bucket_lab01_dev4_tc_category                                                                                                                          = "s3"
  # aws_security_group_sg_00965e59571dd40ce_description                                                                                                           = "launch-wizard-2 created 2021-08-30T18:37:43.252-03:00"
  # aws_security_group_sg_00965e59571dd40ce_egress_cidr_blocks                                                                                                    = ["0.0.0.0/0"]
  # aws_security_group_sg_00965e59571dd40ce_egress_from_port                                                                                                      = 0
  # aws_security_group_sg_00965e59571dd40ce_egress_protocol                                                                                                       = "-1"
  # aws_security_group_sg_00965e59571dd40ce_egress_to_port                                                                                                        = 0
  # aws_security_group_sg_00965e59571dd40ce_ingress_cidr_blocks                                                                                                   = ["0.0.0.0/0"]
  # aws_security_group_sg_00965e59571dd40ce_ingress_from_port                                                                                                     = 22
  # aws_security_group_sg_00965e59571dd40ce_ingress_protocol                                                                                                      = "tcp"
  # aws_security_group_sg_00965e59571dd40ce_ingress_to_port                                                                                                       = 22
  # aws_security_group_sg_00965e59571dd40ce_name                                                                                                                  = "launch-wizard-2"
  # aws_security_group_sg_00965e59571dd40ce_tc_category                                                                                                           = "vpc"
  # aws_security_group_sg_00965e59571dd40ce_vpc_id                                                                                                                = "vpc-9adfb3e7"
  # aws_security_group_sg_035a011a0ac6b0dbd_description                                                                                                           = "launch-wizard-3 created 2021-08-30T18:40:50.146-03:00"
  # aws_security_group_sg_035a011a0ac6b0dbd_egress_cidr_blocks                                                                                                    = ["0.0.0.0/0"]
  # aws_security_group_sg_035a011a0ac6b0dbd_egress_from_port                                                                                                      = 0
  # aws_security_group_sg_035a011a0ac6b0dbd_egress_protocol                                                                                                       = "-1"
  # aws_security_group_sg_035a011a0ac6b0dbd_egress_to_port                                                                                                        = 0
  # aws_security_group_sg_035a011a0ac6b0dbd_ingress_cidr_blocks                                                                                                   = ["0.0.0.0/0"]
  # aws_security_group_sg_035a011a0ac6b0dbd_ingress_from_port                                                                                                     = 22
  # aws_security_group_sg_035a011a0ac6b0dbd_ingress_protocol                                                                                                      = "tcp"
  # aws_security_group_sg_035a011a0ac6b0dbd_ingress_to_port                                                                                                       = 22
  # aws_security_group_sg_035a011a0ac6b0dbd_name                                                                                                                  = "launch-wizard-3"
  # aws_security_group_sg_035a011a0ac6b0dbd_tc_category                                                                                                           = "vpc"
  # aws_security_group_sg_035a011a0ac6b0dbd_vpc_id                                                                                                                = "vpc-9adfb3e7"
  # aws_security_group_sg_072987e0c451e8cd1_description                                                                                                           = "launch-wizard-1 created 2021-08-30T18:33:21.442-03:00"
  # aws_security_group_sg_072987e0c451e8cd1_egress_cidr_blocks                                                                                                    = ["0.0.0.0/0"]
  # aws_security_group_sg_072987e0c451e8cd1_egress_from_port                                                                                                      = 0
  # aws_security_group_sg_072987e0c451e8cd1_egress_protocol                                                                                                       = "-1"
  # aws_security_group_sg_072987e0c451e8cd1_egress_to_port                                                                                                        = 0
  # aws_security_group_sg_072987e0c451e8cd1_ingress_cidr_blocks                                                                                                   = ["0.0.0.0/0"]
  # aws_security_group_sg_072987e0c451e8cd1_ingress_from_port                                                                                                     = 22
  # aws_security_group_sg_072987e0c451e8cd1_ingress_protocol                                                                                                      = "tcp"
  # aws_security_group_sg_072987e0c451e8cd1_ingress_to_port                                                                                                       = 22
  # aws_security_group_sg_072987e0c451e8cd1_name                                                                                                                  = "launch-wizard-1"
  # aws_security_group_sg_072987e0c451e8cd1_tc_category                                                                                                           = "vpc"
  # aws_security_group_sg_072987e0c451e8cd1_vpc_id                                                                                                                = "vpc-9adfb3e7"
  # aws_security_group_sg_09627a4b90bb62da5_description                                                                                                           = "launch-wizard-4 created 2021-08-30T19:12:30.935-03:00"
  # aws_security_group_sg_09627a4b90bb62da5_egress_cidr_blocks                                                                                                    = ["0.0.0.0/0"]
  # aws_security_group_sg_09627a4b90bb62da5_egress_from_port                                                                                                      = 0
  # aws_security_group_sg_09627a4b90bb62da5_egress_protocol                                                                                                       = "-1"
  # aws_security_group_sg_09627a4b90bb62da5_egress_to_port                                                                                                        = 0
  # aws_security_group_sg_09627a4b90bb62da5_ingress_cidr_blocks                                                                                                   = ["0.0.0.0/0"]
  # aws_security_group_sg_09627a4b90bb62da5_ingress_from_port                                                                                                     = 22
  # aws_security_group_sg_09627a4b90bb62da5_ingress_protocol                                                                                                      = "tcp"
  # aws_security_group_sg_09627a4b90bb62da5_ingress_to_port                                                                                                       = 22
  # aws_security_group_sg_09627a4b90bb62da5_name                                                                                                                  = "launch-wizard-4"
  # aws_security_group_sg_09627a4b90bb62da5_tc_category                                                                                                           = "vpc"
  # aws_security_group_sg_09627a4b90bb62da5_vpc_id                                                                                                                = "vpc-9adfb3e7"
  # aws_security_group_sg_afc2b3b2_description                                                                                                                    = "default VPC security group"
  # aws_security_group_sg_afc2b3b2_egress_cidr_blocks                                                                                                             = ["0.0.0.0/0"]
  # aws_security_group_sg_afc2b3b2_egress_from_port                                                                                                               = 0
  # aws_security_group_sg_afc2b3b2_egress_protocol                                                                                                                = "-1"
  # aws_security_group_sg_afc2b3b2_egress_to_port                                                                                                                 = 0
  # aws_security_group_sg_afc2b3b2_ingress_from_port                                                                                                              = 0
  # aws_security_group_sg_afc2b3b2_ingress_protocol                                                                                                               = "-1"
  # aws_security_group_sg_afc2b3b2_ingress_self                                                                                                                   = true
  # aws_security_group_sg_afc2b3b2_ingress_to_port                                                                                                                = 0
  # aws_security_group_sg_afc2b3b2_name                                                                                                                           = "default"
  # aws_security_group_sg_afc2b3b2_tc_category                                                                                                                    = "vpc"
  # aws_security_group_sg_afc2b3b2_vpc_id                                                                                                                         = "vpc-9adfb3e7"
  # aws_subnet_subnet_0838db44_availability_zone                                                                                                                  = "us-east-1a"
  # aws_subnet_subnet_0838db44_cidr_block                                                                                                                         = "172.31.16.0/20"
  # aws_subnet_subnet_0838db44_map_public_ip_on_launch                                                                                                            = true
  # aws_subnet_subnet_0838db44_tc_category                                                                                                                        = "vpc"
  # aws_subnet_subnet_0838db44_vpc_id                                                                                                                             = "vpc-9adfb3e7"
  # aws_subnet_subnet_147a264b_availability_zone                                                                                                                  = "us-east-1b"
  # aws_subnet_subnet_147a264b_cidr_block                                                                                                                         = "172.31.32.0/20"
  # aws_subnet_subnet_147a264b_map_public_ip_on_launch                                                                                                            = true
  # aws_subnet_subnet_147a264b_tc_category                                                                                                                        = "vpc"
  # aws_subnet_subnet_147a264b_vpc_id                                                                                                                             = "vpc-9adfb3e7"
  # aws_subnet_subnet_a0f2ac81_availability_zone_id                                                                                                               = "use1-az2"
  # aws_subnet_subnet_a0f2ac81_cidr_block                                                                                                                         = "172.31.80.0/20"
  # aws_subnet_subnet_a0f2ac81_map_public_ip_on_launch                                                                                                            = true
  # aws_subnet_subnet_a0f2ac81_tc_category                                                                                                                        = "vpc"
  # aws_subnet_subnet_a0f2ac81_vpc_id                                                                                                                             = "vpc-9adfb3e7"
  # aws_subnet_subnet_ac7f2cca_availability_zone                                                                                                                  = "us-east-1c"
  # aws_subnet_subnet_ac7f2cca_cidr_block                                                                                                                         = "172.31.0.0/20"
  # aws_subnet_subnet_ac7f2cca_map_public_ip_on_launch                                                                                                            = true
  # aws_subnet_subnet_ac7f2cca_tc_category                                                                                                                        = "vpc"
  # aws_subnet_subnet_ac7f2cca_vpc_id                                                                                                                             = "vpc-9adfb3e7"
  # aws_subnet_subnet_d22530dc_availability_zone                                                                                                                  = "us-east-1f"
  # aws_subnet_subnet_d22530dc_cidr_block                                                                                                                         = "172.31.64.0/20"
  # aws_subnet_subnet_d22530dc_map_public_ip_on_launch                                                                                                            = true
  # aws_subnet_subnet_d22530dc_tc_category                                                                                                                        = "vpc"
  # aws_subnet_subnet_d22530dc_vpc_id                                                                                                                             = "vpc-9adfb3e7"
  # aws_subnet_subnet_f391f6c2_availability_zone_id                                                                                                               = "use1-az3"
  # aws_subnet_subnet_f391f6c2_cidr_block                                                                                                                         = "172.31.48.0/20"
  # aws_subnet_subnet_f391f6c2_map_public_ip_on_launch                                                                                                            = true
  # aws_subnet_subnet_f391f6c2_tc_category                                                                                                                        = "vpc"
  # aws_subnet_subnet_f391f6c2_vpc_id                                                                                                                             = "vpc-9adfb3e7"
  # aws_vpc_vpc_9adfb3e7_cidr_block                                                                                                                               = "172.31.0.0/16"
  # aws_vpc_vpc_9adfb3e7_enable_dns_hostnames                                                                                                                     = true
  # aws_vpc_vpc_9adfb3e7_enable_dns_support                                                                                                                       = true
  # aws_vpc_vpc_9adfb3e7_instance_tenancy                                                                                                                         = "default"
  # aws_vpc_vpc_9adfb3e7_tc_category                                                                                                                              = "vpc"
  source = "./module-iac_aws_samuel"
}

provider "aws" {
  region = var.region
}


terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }

  }

  required_version = ">= 1.0"
}

variable "region" {
  default = "us-east-1"
}

